---

- name: server
  hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: Software is installed
      yum:
        name:
          - net-snmp
        state: present

    - name: Access via 161 port
      firewalld:
        port: "{{ item.port }}"
        permanent: yes
        immediate: yes
        state: enabled
      with_items:
        - { port: '161/tcp' }

    - name: reload service firewalld
      systemd:
        name: firewalld
        state: reloaded

    - name: Enable snmpd service
      service:
        name: snmpd
        state: enabled
        notify: Restart snmpd

    - name: Template snmpd.conf
      template:
        src: {{ source_file }}
        dest: {{ dest_file }}
        owner: root
        group: root
        mode: 0644
        backup: yes
      vars:
        source_file: /home/it/ansible/Learning/ansible-course/student_files/02/templates/snmpd.j2
        dest_file: /etc/snmp/snmpd.conf

  handlers:
    - name: Restart snmpd
      action:
        service:
          name: snmpd
          state: restarted